name: docs

permissions:
    contents: write

on:
    push:
        branches: [main]
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    publish:
        runs-on: ubuntu-latest
        env:
            RUSTDOCFLAGS: -Dwarnings
        steps:
            - uses: actions/checkout@v5
            - uses: dtolnay/rust-toolchain@nightly
            - uses: dtolnay/install@cargo-docs-rs
            - run: cargo docs-rs --target-dir target
            - name: Add index
              run: |
                  echo '<meta http-equiv="refresh" content="0; url=erudite">' > target/x86_64-unknown-linux-gnu/doc/index.html
            - name: Deploy to GitHub Pages
              if: ${{ github.event_name != 'pull_request' }}
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
                  publish_dir: target/x86_64-unknown-linux-gnu/doc
